# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b1750308139c9920548207b7287378c9d9349811ec5dd14b2bf47c3f219659dc1b0d5b4536c2d7d4bac2ab4b85bcd19a3bb23423eba3bd5990ee52053ef08bf

test:
  secret_key_base: 38514da96f768e90380771dd99fb127224a13bf57468de9a0bb4f3bcd00bd9a0846f2743cdaff64929a61f26710f2b44032eec02dcd9c932932a20026f48a444

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
